# ---==== Common Inputs used by all algorithm ========================================--- #

# === Input files paths ===---------------------------------- #
# TOML configuration file
config_file = ""
# VHM 10m as main TBk input
vhm_10m = ""
# VHM 150cm to calculate DG
vhm_150cm = ""
# Coniferous raster to calculate stand mean
coniferous_raster = ""
# Coniferous raster for classification
coniferous_raster_for_classification = ""
# Perimeter to clip final result
perimeter = ""

# === Output paths ===--------------------------------------- #
# Folder in which to save the results output folder
output_root = ""

# === Other ===---------------------------------------------- #
# Need to delete temporary files and fields
del_tmp = true


# ---==== TBK preprocessing Algorithm ================================================--- #

# Mask shapefile to clip final result
mask = ""

# === Prepare MG ===----------------------------------------- #
# Maximum deciduous wood value
max_lh = 5000
# Maximum coniferous wood value
max_nh = 10000
# Mixing degree 10m input (.tif)
mg_input = ""
# Mixing degree output name (.tif)
mg_output = "MG.tif"
# Minimum deciduous wood value
min_lh = 1
# Minimum coniferous wood value
min_nh = 5000
reclassify_mg_values = true


# === Prepare VHM ===---------------------------------------- #
# Convert VHM to BYTE datatype
convert_to_byte = true
# Crop VHM to mask
crop_vhm = true
# Rasterize mask
rasterize_mask = false
# VHM max value
vMax = 60.0
# VHM min value
vMin = 0.0
# VHM NA value
vNA = 255
# VHM detail output name (.tif)
vhm_detail = "vhm_detail.tif"
# Detailed input VHM (.tif)
vhm_input = ""

# ---==== TBK Main Algorithm =========================================================--- #

# === LOG FILE ===------------------------------------------- #
# will be stored in the result directory (bk_process)
logfile_name = "tbk_processing.log"

# === Main TBk parameters ===-------------------------------- #
# (for details see run_stand_classification function)
# Short description
description = "TBk dataset"
# Need to use the coniferous raster for classification
useConiferousRasterForClassification = true
# Relative min tolerance
min_tol = 0.1
# Relative max tolerance
max_tol = 0.1
# Extension of the range down [m]
min_corr = 4
# Extension of the range up [m]
max_corr = 4
# Minimum relative amount of valid cells
min_valid_cells = 0.5
# Minimum cells per stand
min_cells_per_stand = 10
# Minimum cells for pure mixture stands
min_cells_per_pure_stand = 30
# VHM minimum height
vhm_min_height = 0
# VHM maximum height
vhm_max_height = 60

# === Additional parameters ===------------------------------ #
# Min. area to eliminate small stands
min_area_m2 = 1000
# Min. area to merge similar stands
similar_neighbours_min_area = 2000
# hdom relative diff to merge similar stands
similar_neighbours_hdom_diff_rel = 0.15
# Also calc coniferous prop. for main layer
calc_mixture_for_main_layer = true
# Simplification tolerance
simplification_tolerance = 8

# === Additional Layer ===------------------------------------ #
# Default Vegetation Zone
vegZoneDefault = 2
# Vegetation Zone layer (polygons) for spatial join
vegZoneLayer = ""
# Vegetation Zone Code field (in layer)
vegZoneLayerField = ""
# Default Forest Site Category
forestSiteDefault = ""
# Forest Site Category layer (polygons) for spatial join
forestSiteLayer = ""
# Forest Site Category field (in layer)
forestSiteLayerField = ""


